name: LHDsim
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.14
  - scipy
  - numba
  - networkx
  - python-igraph
  - selenium
  - numpy
  - pandas
  - matplotlib
  - pytest
  - ipykernel
  - pyarrow
prefix: /opt/miniconda3/envs/LHDsim
