name: testEnv
channels:
  - conda-forge
  - defaults
  - Conda-Forge
dependencies:
  - _python_abi3_support=1.0
  - appdirs=1.4.4
  - appnope=0.1.4
  - arpack=3.9.1
  - asttokens=3.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - black=19.3b0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.14.0
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.14.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - igraph=0.10.16
  - importlib-metadata=8.7.0
  - importlib_metadata=8.7.0
  - iniconfig=2.1.0
  - ipykernel=7.1.0
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.17.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.11.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - line_profiler=5.0.0
  - llvm-openmp=21.1.4
  - lz4-c=1.10.0
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nlohmann_json=3.12.0
  - numpy=2.3.4
  - openjpeg=2.5.3
  - openssl=3.6.0
  - orc=2.2.1
  - outcome=1.3.0.post0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - plotext=5.3.2
  - pluggy=1.5.0
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycairo=1.28.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - pytest=8.4.2
  - pytest-mock=3.15.1
  - python=3.14.0
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.0
  - python-igraph=0.11.9
  - python-tzdata=2025.2
  - python_abi=3.14
  - pytz=2025.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - randomgen=2.3.0
  - re2=2025.11.05
  - readline=8.3
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - selenium=4.38.0
  - selenium-manager=4.38.0
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - texttable=1.7.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - toml=0.10.2
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trio=0.32.0
  - trio-websocket=0.12.2
  - tuna=0.5.11
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - websocket-client=1.9.0
  - wheel=0.45.1
  - wsproto=1.3.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - antimony==3.1.0
      - cayenne==1.0.3
      - cython==3.1.6
      - llvmlite==0.46.0b1
      - numba==0.63.0b1
      - snakeviz==2.2.2
prefix: /opt/miniconda3/envs/testEnv
