name: testEnv
channels:
  - conda-forge
  - defaults
  - Conda-Forge
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - arpack=3.9.1=nompi_h1f29f7c_102
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h41ebd0a_3
  - aws-c-cal=0.9.2=hd08b81e_1
  - aws-c-common=0.12.4=h6caf38d_0
  - aws-c-compression=0.3.1=habbe1e8_6
  - aws-c-event-stream=0.5.6=hf65d68d_3
  - aws-c-http=0.10.4=h70a9c10_3
  - aws-c-io=0.22.0=h89d1e94_1
  - aws-c-mqtt=0.13.3=he7b126b_6
  - aws-c-s3=0.8.6=h7a3c519_5
  - aws-c-sdkutils=0.2.4=habbe1e8_1
  - aws-checksums=0.2.7=habbe1e8_2
  - aws-crt-cpp=0.34.4=h01415d0_0
  - aws-sdk-cpp=1.11.606=h2169b1b_4
  - azure-core-cpp=1.16.0=h88fedcc_1
  - azure-identity-cpp=1.12.0=hd83eed2_0
  - azure-storage-blobs-cpp=12.14.0=he094cc7_1
  - azure-storage-common-cpp=12.10.0=h12fd690_2
  - azure-storage-files-datalake-cpp=12.12.0=h30213e0_3
  - black=19.3b0=py_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - brotli-python=1.1.0=py314he8615de_4
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=1.17.1=py314hc2abb23_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.2.1=py314hca03da5_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314h6b18a25_2
  - cpython=3.14.0=py314hd8ed1ab_102
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py314hac9ea21_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - fontconfig=2.15.0=h1383a14_1
  - fonttools=4.60.1=pyh7db6752_0
  - freetype=2.14.1=hce30654_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - gflags=2.2.2=hf9b8971_1005
  - glog=0.7.1=heb240a5_0
  - glpk=5.0=h6d7a090_0
  - gmp=6.3.0=h7bae524_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=hc8870d7_0
  - idna=3.11=pyhd8ed1ab_0
  - igraph=0.10.16=hb134b8e_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - iniconfig=2.1.0=py314hca03da5_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.9=py314hb140f16_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libarrow=21.0.0=hd43feaf_8_cpu
  - libarrow-acero=21.0.0=hc317990_8_cpu
  - libarrow-compute=21.0.0=h75845d1_8_cpu
  - libarrow-dataset=21.0.0=hc317990_8_cpu
  - libarrow-substrait=21.0.0=h144af7f_8_cpu
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libblas=3.9.0=37_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.84.4=h7a3292d_0
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=37_hd9741b5_openblas
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_2
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=21.0.0=h45c8936_8_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsodium=1.0.20=h99b78c6_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.0=hfce79cd_1
  - libutf8proc=2.11.2=hd2415e0_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - line_profiler=5.0.0=py314hb140f16_1
  - llvm-openmp=21.1.4=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - matplotlib=3.10.7=py314he55896b_0
  - matplotlib-base=3.10.7=py314hd63e3f0_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - nlohmann_json=3.12.0=h248ca61_1
  - numpy=2.3.4=py314h5b5928d_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - outcome=1.3.0.post0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314ha3d490a_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py314haf93fec_3
  - pip=25.2=pyh0d26453_1
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotext=5.3.2=pyhff2d567_0
  - pluggy=1.5.0=py314hca03da5_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py314h0612a62_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=21.0.0=py314he55896b_1
  - pyarrow-core=21.0.0=py314hf20a12a_1_cpu
  - pycairo=1.28.0=py314h138ad6a_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=py314hca03da5_0
  - pytest-mock=3.15.1=py314hca03da5_0
  - python=3.14.0=h1858270_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.0=h4df99d1_102
  - python-igraph=0.11.9=py314h93ecee7_3
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=1_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - randomgen=2.3.0=py314hdcf55e8_1
  - re2=2025.11.05=h64b956e_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py314hcc665ce_0
  - scipy=1.16.2=py314h624bdf2_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - selenium=4.38.0=pyhcf101f3_0
  - selenium-manager=4.38.0=h8d80559_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py314hdcf55e8_1
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.5.2=py314hb84d1df_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trio=0.32.0=py314h77f9db9_1
  - trio-websocket=0.12.2=pyh29332c3_0
  - tuna=0.5.11=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py314hb84d1df_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wsproto=1.3.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.25.0=py314h163e31d_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - antimony==3.1.0
      - cayenne==1.0.3
      - cython==3.1.6
      - llvmlite==0.46.0b1
      - numba==0.63.0b1
      - snakeviz==2.2.2
prefix: /opt/miniconda3/envs/testEnv
